sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--no-interaction"

before_install:
  - composer self-update
  - phpenv config-add tests/travis.php.ini

install:
  # Install dependencies
  - travis_retry composer update $COMPOSER_FLAGS
  - composer info -i
  # Install node
  - nvm install 8
  - npm install -g npm
  - npm install
  # Create database for build test
  - bin/adminconsole doctrine:database:create
  # Create database for unit test
  - bin/adminconsole doctrine:database:create --env=test

script:
  # Test if installation works
  - bin/adminconsole sulu:build dev --no-interaction
  # Test if PHPUnit installation works
  - SYMFONY_ENV=test bin/simple-phpunit
  # Lint Twig files
  - bin/adminconsole lint:twig app/Resources/views
  # Lint Yaml files
  - bin/adminconsole lint:yaml app/config
  # Test webpack build
  - npm run build
