sudo: false

language: php

services:
    - mysql

cache:
  directories:
    - "$HOME/.composer/cache/files"

before_install:
  - composer self-update
  - phpenv config-add tests/travis.php.ini

matrix:
  include:
    # With ENVIRONMENT variables
    - php: 7.2
      install:
        # Install dependencies
        - travis_retry composer update $COMPOSER_FLAGS
        - composer info -i
        # Create database for build test
        - bin/adminconsole doctrine:database:create
      env:
        - APP_ENV=test
        - APP_SECRET=a448d1dfcaa563fce56c2fd9981f662b
        - MAILER_URL=null://localhost
        - SULU_ADMIN_EMAIL=
        - DATABASE_URL=mysql://root:@127.0.0.1/sulu_test
        - COMPOSER_FLAGS="--no-interaction"

    # Without ENVIRONMENT variables
    - php: 7.3
      install:
        - composer create-project sulu/sulu-minimal ../test-create-project-dir --repository="{\"type\":\"path\",\"url\":\"./\"}" --stability=dev -n
        - cd ../test-create-project-dir
        - echo 'DATABASE_URL=mysql://root:@127.0.0.1:3306/sulu_test' >> .env.local
      env:
        - NPM_BUILD: true

script:
  - pwd
  - |
    if [[ $NPM_BUILD = true ]]; then
        nvm install 12
        npm install
        npm run build
    fi
  - composer validate --strict
  - bin/adminconsole sulu:build dev --no-interaction
  - bin/adminconsole doctrine:schema:validate
  - vendor/bin/simple-phpunit
  - bin/adminconsole lint:twig templates
  - bin/adminconsole lint:yaml config
