build: false

platform:
    - x64

environment:
    APP_ENV: test
    APP_SECRET: a448d1dfcaa563fce56c2fd9981f662b
    MAILER_URL: null://localhost
    SULU_ADMIN_EMAIL: example@localhost
    PHPCR_TRANSPORT: doctrinedbal
    DATABASE_URL: mysql://root:Password12!@127.0.0.1/sulu_test
    DATABASE_CHARSET: utf8mb4
    DATABASE_COLLATE: utf8mb4_unicode_ci
    NODEJS_VERSION: "12"
    matrix:
        - PHP_VERSION: 7.2.4

services:
    - mysql

hosts:
    localhost: 127.0.0.1

init:
    - SET PATH=C:\tools\php;C:\tools\composer;%PATH%

cache:
    - '%APPDATA%\Composer'
    - '%LOCALAPPDATA%\Composer'
    - C:\tools\php -> appveyor.yml
    - C:\tools\composer\composer.phar -> appveyor.yml

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - ps: Install-Product node $env:NODEJS_VERSION

    - IF NOT EXIST C:\tools (
          mkdir C:\tools
      )

    - IF NOT EXIST C:\tools\composer (
          mkdir C:\tools\composer
      )

    - IF NOT EXIST C:\tools\composer\composer.phar (
          cd C:\tools\composer
          && appveyor DownloadFile https://getcomposer.org/composer.phar
      )

    - IF NOT EXIST C:\tools\php (
          cinst --yes --allow-empty-checksums php --version %PHP_VERSION% --params '/InstallDir:C:\tools\php'
      )

    - cd C:\tools\php
    - ps: cat php.ini-production | %{$_ -replace "memory_limit = 128M","memory_limit = -1"} | Out-File -Encoding "Default" php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_gd2.dll >> php.ini
    - echo extension=php_intl.dll >> php.ini
    - echo extension=php_pdo_mysql.dll >> php.ini
    - echo extension=php_pdo_sqlite.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - php -i

before_test:
    - cd %APPVEYOR_BUILD_FOLDER%
    - php -dmemory_limit=-1 C:\tools\composer\composer.phar update --no-interaction --no-progress --prefer-dist --no-ansi

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - php bin/adminconsole sulu:build dev --no-interaction
    - php bin/phpunit
    - php bin/adminconsole lint:twig templates
    - php bin/adminconsole lint:yaml config
    - cd assets/admin
    - npm install
    - npm run build
