imports:
    - { resource: security.yml }
    - { resource: ../config.yml }

# SuluAdmin Configuration
sulu_admin:
    name: "%sulu_admin.name%"
    email: "%sulu_admin.email%"

# SuluDocumentManager Configuration
sulu_document_manager:
    default_session: default
    live_session: live

