imports:
    - { resource: security.yml }
    - { resource: ../config.yml }

# SuluAdmin Configuration
sulu_admin:
    name: "%sulu_admin.name%"
    email: "%sulu_admin.email%"

framework:
    assets:
        json_manifest_path: "%kernel.project_dir%/web/manifest.json"
