imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator: { fallbacks: ["%locale%"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/%sulu.context%/routing_%kernel.environment%.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.var_dir%/sessions/%sulu.context%/%kernel.environment%"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "%database_version%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# DoctrineCache Configuration
doctrine_cache:
    providers:
        phpcr_meta:
            type: "%phpcr_cache%"
        phpcr_nodes:
            type: "%phpcr_cache%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# MassiveSearch Configuration
massive_search:
    adapters:
        zend_lucene:
            basepath: "%kernel.var_dir%/indexes"

# JMS Serializer Configuration
jms_serializer:
    metadata:
        debug: "%kernel.debug%"

# SuluCore Configuration
sulu_core:
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
            paths:
                homepage:
                    path: "%kernel.root_dir%/Resources/templates/pages"
                    type: "home"
                page:
                    path: "%kernel.root_dir%/Resources/templates/pages"
                    type: "page"
                snippet:
                    path: "%kernel.root_dir%/Resources/templates/snippets"
                    type: "snippet"

# SuluDocumentManager Configuration
sulu_document_manager:
    sessions:
        default:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"
        live:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%_live"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"

# SuluWebsocket Configuration
sulu_websocket:
    server:
        http_host: "%websocket_url%"
        port: "%websocket_port%"

sulu_website:
    sitemap:
        dump_dir: "%kernel.var_dir%/sitemaps"

# SuluHttpCache Configuration
sulu_http_cache:
    handlers:
        debug:
            enabled: "%kernel.debug%"

# SuluMedia Configuration
sulu_media:
    storage:
        local:
            path: "%kernel.var_dir%/uploads/media"

dubture_f_fmpeg:
    ffmpeg_binary: /usr/local/bin/ffmpeg # path to ffmpeg
    ffprobe_binary: /usr/local/bin/ffprobe # path to ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 4

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
services:
    jms_serializer.cache_naming_strategy: "@sulu_core.serialize_caching_strategy"

