imports:
    - { resource: security.yml }
    - { resource: ../config.yml }

# Twig Configuration
twig:
    exception_controller: sulu_website.exception.controller:showAction

# SymfonyCMF Configuration
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            cmf_routing.dynamic_router: 20
    dynamic:
        enabled: true
        route_provider_service_id: sulu_website.provider.content

